import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import "reshaped/themes/slate/theme.css";
import "./globals.css";

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" data-rs-theme="slate" data-rs-color-mode="dark">
			<body className={`${geistMono.variable} antialiased`}>
				{/* <Reshaped theme="slate" defaultColorMode="dark"> */}
				{children}
				{/* </Reshaped> */}
			</body>
		</html>
	);
}
